### ISSUE TITLE
Re-crop outfit images

### ISSUE THREAD

**Issue by Jimmy-sheep** [fabiobarcelona/Cult-of-the-Lamb-Save-Editor#1]
Hello, I try to crop the outfit images again...

![0](https://user-images.githubusercontent.com/65125836/200162084-50bc3667-bb26-4a97-b877-129216c286a0.png)
![1](https://user-images.githubusercontent.com/65125836/200162085-53af0cba-91d6-4ede-91a8-4a1c767c23a8.png)
![2](https://user-images.githubusercontent.com/65125836/200162087-02e560cf-aa24-4cdb-8352-d811425c42a7.png)
![3](https://user-images.githubusercontent.com/65125836/200162089-e288473e-8359-445c-b021-7739319e4b54.png)
![7](https://user-images.githubusercontent.com/65125836/200162090-386e395d-11e2-47e7-a364-0deca2e260de.png)
![8](https://user-images.githubusercontent.com/65125836/200162083-9ef3734e-fa29-4fa2-9cc8-e49ec31e5054.png)

**Comment by fabiobarcelona** [comment]
Thank you! I will update them once I release the next update :)
